<?php
/**
 * @global $APPLICATION CMain
 */

require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Подписывайтесь на наш блог, чтобы быть в курсе последних новостей и инсайтов интернет-маркетинга.");
$APPLICATION->SetPageProperty("TITLE", "Блог Digital-агентства IZIFIR - последние новости и инсайты интернет-маркетинга");
$APPLICATION->SetTitle("Блог");
?><?
$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"blog", 
	array(
		"COMPONENT_TEMPLATE" => "blog",
		"IBLOCK_TYPE" => "blog",
		"IBLOCK_ID" => \Nicedo\Core\Helpers\Tools::getIblockIdByCode("blog_articles"),
		"NEWS_COUNT" => "9",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "N",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "blogFilter",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/blog/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "AUTHOR",
			2 => "TIME_TO_READ",
			3 => "CATEGORY",
			4 => "VIEWS_COUNT",
			5 => "DISLIKES",
			6 => "LIKES",
			7 => "RATING",
			8 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "AUTHOR",
			2 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "AUTHOR",
			2 => "TIME_TO_READ",
			3 => "CATEGORY",
			4 => "VIEWS_COUNT",
			5 => "DISLIKES",
			6 => "LIKES",
			7 => "RATING",
			8 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => "ajax",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Показать ещё",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"FILE_404" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"OTHER_ARTICLES_NEWS_COUNT" => "3",
		"COMMENTS_NEWS_COUNT" => "2",
		"OTHER_ARTICLES_TITLE" => "Другие статьи",
		"AUTHOR_OTHER_ARTICLES_TITLE" => "Статьи автора",
		"COMMENT_ARTICLES_TITLE" => "Оставьте отзыв",
		"FORM_BLOCK_ID" => "6",
		"FORM_SECTION_ID" => "177",
		"SEF_URL_TEMPLATES" => array(
			"author" => "author/#AUTHOR_CODE#/",
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
			"smart_filter" => "filter/#SMART_FILTER_PATH#/apply/",
		)
	),
	false
);
?><?php require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>